# AgriBORA Maize Price Forecasting
## 1. Data Cleaning & Preprocessing

This notebook loads and cleans:
- agriBORA data
- KAMIS data
- Final validation data

Goal:
Prepare clean datasets for modeling.

In [2]:
#import the neccessary file and set the path

import sys
from google.colab import drive


# Mount Google Drive
drive.mount('/content/drive')

# Define the path to your folder in Google Drive
# Example: If your folder is in "My Drive/Data Science/Jupyter Notebooks/data"
PROJECT_PATH = "/content/drive/Shareddrives/Data Science/Commodity Price Forecasting/Internship Work by Jairus Odhiambo/Jupyter Notebooks"


sys.path.insert(0, PROJECT_PATH)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
from data.data_loader import *
from data.preprocessing import *

In [5]:
import pandas as pd
import numpy as np

In [6]:
#Load data


data=load_all_data()

target_counties=get_target_counties()

============================================================
ERROR LOADING FILE
/content/drive/MyDrive/Agribora_Final/data/agriBORA_maize_prices.csv
[Errno 2] No such file or directory: '/content/drive/MyDrive/Agribora_Final/data/agriBORA_maize_prices.csv'
============================================================
============================================================
ERROR LOADING FILE
/content/drive/MyDrive/Agribora_Final/data/agriBORA_maize_prices_weeks_46_to_51.csv
[Errno 2] No such file or directory: '/content/drive/MyDrive/Agribora_Final/data/agriBORA_maize_prices_weeks_46_to_51.csv'
============================================================
============================================================
ERROR LOADING FILE
/content/drive/MyDrive/Agribora_Final/data/kamis_maize_prices.csv
[Errno 2] No such file or directory: '/content/drive/MyDrive/Agribora_Final/data/kamis_maize_prices.csv'
============================================================
============================================================
ERROR LOADING FILE
/content/drive/MyDrive/Agribora_Final/data/kamis_maize_prices_raw.csv
[Errno 2] No such file or directory: '/content/drive/MyDrive/Agribora_Final/data/kamis_maize_prices_raw.csv'
============================================================
============================================================
ERROR LOADING FILE
/content/drive/MyDrive/Agribora_Final/data/agriBORA_Final_Weeks_maize_price.csv
[Errno 2] No such file or directory: '/content/drive/MyDrive/Agribora_Final/data/agriBORA_Final_Weeks_maize_price.csv'
============================================================

All datasets loaded successfully

In [7]:
#Targeted counties

print(target_counties)

['Kiambu', 'Kirinyaga', 'Mombasa', 'Nairobi', 'Uasin-Gishu']

Extract dataset

In [8]:
agri_df = data['agri_df']

agriW51_df = data['agriW51_df']

kamis_df = data['kamis']

kamis_raw_df = data['kamis_raw']

finalW_df = data['finalW_df']

In [13]:
data

{'agri_df': None,
 'agriW51_df': None,
 'kamis': None,
 'kamis_raw': None,
 'finalW_df': None}

In [11]:
agri_df

In [9]:
print(agri_df.shape)

print(agriW51_df.shape)

print(kamis_df.shape)

print(kamis_raw_df.shape)

print(finalW_df.shape)

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
agri_clean =clean_agri_data(
    agri_df,
    agriW51_df,
    target_counties
)

display(agri_clean.head())

============================================================
CLEANING AGRIBORA DATA
============================================================
Final shape: (232, 6)

   County       Date  WholeSale Commodity_Classification Year_Week  WeekofYear
0  Kiambu 2023-10-02      46.67          Dry_White_Maize   2023-40          40
1  Kiambu 2024-01-15      47.78          Dry_White_Maize   2024-03           3
2  Kiambu 2024-02-05      47.78          Dry_White_Maize   2024-06           6
3  Kiambu 2024-02-12      44.44          Dry_White_Maize   2024-07           7
4  Kiambu 2024-03-04      37.78          Dry_White_Maize   2024-10          10

Before cleaning the kamis data information.

In [ ]:
# Kamis dataset

kamis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21888 entries, 0 to 21887
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Commodity_Classification  21888 non-null  object
 1   Commodity                 21888 non-null  object
 2   Classification            21888 non-null  object
 3   County                    21888 non-null  object
 4   Market                    21888 non-null  object
 5   Date                      21888 non-null  object
 6   Year                      21888 non-null  int64
 7   Month                     21888 non-null  int64
 8   Year_Month                21888 non-null  object
 9   WeekofYear                21888 non-null  int64
 10  Year_Week                 21888 non-null  object
 11  SupplyVolume              17382 non-null  float64
 12  Retail                    21016 non-null  float64
 13  Wholesale                 20203 non-null  float64
 14  Unit                      21888 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 2.5+ MB

In [ ]:
# Clean Kamis data
kamis_clean = clean_kamis_data(
    data['kamis'],
    target_counties
)

kamis_clean.head()

,County,Date,WholeSale,Commodity_Classification,Year_Week,WeekofYear
0,Kirinyaga,2022-01-03,37.78,Dry_White_Maize,2022-01,1
1,Kirinyaga,2022-01-03,30.00,Dry_White_Maize,2022-01,1
2,Kirinyaga,2022-01-04,33.33,Dry_White_Maize,2022-01,1
3,Nairobi,2022-01-04,38.00,Dry_White_Maize,2022-01,1
4,Uasin-Gishu,2022-01-05,24.00,Dry_White_Maize,2022-01,1

In [ ]:
kamis_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2594 entries, 0 to 2593
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   County                    2594 non-null   object
 1   Date                      2594 non-null   datetime64[ns]
 2   WholeSale                 2594 non-null   float64
 3   Commodity_Classification  2594 non-null   object
 4   Year_Week                 2594 non-null   object
 5   WeekofYear                2594 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 121.7+ KB

In [ ]:
kamis_clean.isna().sum()

County                      0
Date                        0
WholeSale                   0
Commodity_Classification    0
Year_Week                   0
WeekofYear                  0
dtype: int64

In [ ]:
kamis_clean.duplicated().sum()

np.int64(0)

In [ ]:
#Solution to duplicates

before = len(kamis_clean)

kamis_clean = kamis_clean.drop_duplicates().reset_index(drop=True)

after = len(kamis_clean)

print(f"Rows before: {before}")
print(f"Rows after:  {after}")
print(f"Duplicates removed: {before - after}")

# =========================================
# VERIFY CLEANING
# =========================================

print("\n" + "="*50)
print("VERIFYING CLEAN DATA")
print("="*50)

remaining_duplicates = kamis_clean[kamis_clean.duplicated(keep=False)]

print(f"Remaining duplicates: {len(remaining_duplicates)}")

Rows before: 2594
Rows after:  2594
Duplicates removed: 0

==================================================
VERIFYING CLEAN DATA
==================================================
Remaining duplicates: 0

In [ ]:
kamis_raw_clean = clean_kamis_raw_data(
    kamis_raw_df,
    target_counties
)

display(kamis_raw_clean.head())

Final Shape: (1765, 6)

   County       Date  WholeSale Commodity_Classification Year_Week  WeekofYear
0  Kiambu 2022-01-10      37.22          Dry_White_Maize    2022_3           3
1  Kiambu 2022-01-17      37.22          Dry_White_Maize    2022_4           4
2  Kiambu 2022-01-27      38.89          Dry_White_Maize    2022_5           5
3  Kiambu 2022-02-03      38.89          Dry_White_Maize    2022_6           6
4  Kiambu 2022-05-19      47.78          Dry_White_Maize   2022_21          21